model:
  class_path: incremental_supersimple.IncrementalSuperSimpleNet
  init_args:
    beta: 0.1
trainer:
  max_epochs: 1
  accelerator: auto
  devices: 1
  precision: 32
  enable_checkpointing: true
  enable_progress_bar: true
  log_every_n_steps: 10
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: image_AUROC
        mode: max
        save_top_k: 1
        filename: "best_model"
        auto_insert_metric_name: false
logging:
  log_graph: false
seed_everything: 42
